#!/usr/bin/env bash

TERRAFORM_DIR="terraform"
TERRAFORM_SECRETS_MANIFEST_FP="${TERRAFORM_DIR}/secrets.manifest"
source "${TERRAFORM_DIR}/env.sh"

decrypt_file() {
    KEY_NAME=${1}
    PLAINTEXT_FILE=${2}
    gcloud kms decrypt \
    --project=${TF_VAR_gcp_project} \
    --location=${TF_VAR_region}  \
    --keyring=${TF_VAR_secrets_key_ring_name} \
    --key=${KEY_NAME} \
    --plaintext-file=${PLAINTEXT_FILE} \
    --ciphertext-file="${PLAINTEXT_FILE}.enc"
}

decrypt() {
    for f in $(cat ${TERRAFORM_SECRETS_MANIFEST_FP}); do
        decrypt_file ${TF_VAR_tf_secrets_key_name} "${TERRAFORM_DIR}/${f}"
    done
}

encrypt_file() {
    KEY_NAME=${1}
    PLAINTEXT_FILE=${2}
    gcloud kms encrypt \
    --project=${TF_VAR_gcp_project} \
    --location=${TF_VAR_region}  \
    --keyring=${TF_VAR_secrets_key_ring_name} \
    --key=${KEY_NAME} \
    --plaintext-file=${PLAINTEXT_FILE} \
    --ciphertext-file="${PLAINTEXT_FILE}.enc"
}

encrypt() {
    for f in $(cat ${TERRAFORM_SECRETS_MANIFEST_FP}); do
        encrypt_file ${TF_VAR_tf_secrets_key_name} "${TERRAFORM_DIR}/${f}"
    done
}

cmd=${1}
case ${cmd} in
    "decrypt")
        decrypt
        ;;
    "encrypt")
        encrypt
        ;;
    "clean")
        cat ${TERRAFORM_SECRETS_MANIFEST_FP} | xargs -I {} rm "${TERRAFORM_DIR}/{}"
        ;;
    *)
        echo 'Usage: secrets [decrypt|encrypt|clean]'
esac
