apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: k8s-snapshots
  name: k8s-snapshots
  namespace: default
rules:
  - apiGroups:
      - "k8s-snapshots.elsdoerfer.com"
    resources:
      - snapshotrules
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: k8s-snapshots
  name: k8s-snapshots
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-snapshots
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-snapshots
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-snapshots
    spec:
      volumes:
      - name: gcp-credentials
        secret:
          secretName: gcp-credentials
      containers:
      - name: k8s-snapshots
        image: elsdoerfer/k8s-snapshots:v2.0
        volumeMounts:
        - name: gcp-credentials
          mountPath: /var/secrets/gcp-credentials
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/gcp-credentials/gcp_credentials.json
        - name: SNAPSHOT_DATETIME_FORMAT
          value: '%Y%m%d-%H%M%S'

