---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: libri-experimenter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: User
  name: libri-admin@elixir-deploy-staging-1.iam.gserviceaccount.com
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: libri-experimenter
spec:
  restartPolicy: Never
  volumes:
  - name: data
    emptyDir: {}
  containers:
  - name: libri-experimenter
    image: daedalus2718/libri-exp:snapshot-f3e6f23
    args: [
      "run",
      "--librarians",               "35.227.54.0:30100,35.237.0.109:30101,35.227.54.0:30102,35.237.0.109:30103,35.237.0.109:30104,35.227.54.0:30105,35.227.54.0:30106,35.237.0.109:30107",
      "--duration",                 "168h",
      "--numAuthors",               "1",
      "--docsPerDay",               "1440",  # 1 doc per minute
      "--contentSizeKBGammaShape",  "1.5",
      "--contentSizeKBGammaRate",   "0.00588",
      "--sharesPerUpload",          "2",
      "--nUploaders",               "64",
      "--nDownloaders",             "64",
    ]
    env:
    - name: GODEBUG         # ensure we use the pure Go (rather than CGO) DNS
      value: netdns=go      # resolver (see https://golang.org/src/net/net.go)
    volumeMounts:
    - name: data
      mountPath: /data
    resources:
      limits:
        memory: 250M
        cpu: 100m
